spring.application.name=bank_rest

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_cards
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.liquibase.change-log=classpath:/db/migration/db.migration-master.yaml
