spring.application.name=bank_rest

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_cards
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/migration/changelog-master.yaml